/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/businesses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tracked businesses, highest priority first */
        get: operations["listBusinesses"];
        put?: never;
        /**
         * Start tracking businesses from website addresses
         * @description New businesses are queued for an audit. Invalid addresses are reported in `skipped`, and websites that are already tracked are returned without being duplicated.
         */
        post: operations["trackBusinesses"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/businesses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one business with the evidence and contacts from its latest audit */
        get: operations["getBusiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/businesses/{id}/audits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue a new audit of the business */
        post: operations["auditBusiness"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Business: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            source: "url" | "csv" | "places";
            placeId: string | null;
            /** @example https://klinik.co.id/ */
            websiteUrl: string | null;
            displayName: string | null;
            /** @enum {string} */
            status: "new" | "contacted" | "replied" | "meeting" | "won" | "lost";
            /** @description Geometric mean of the latest need and capacity scores */
            priority: number | null;
            latestAudit: components["schemas"]["Audit"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Audit: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            /** @description How much the business needs the agency (0–100) */
            needScore: number | null;
            /** @description How established the business is (0–100) */
            capacityScore: number | null;
            error: string | null;
            /** @description How the audit ran, e.g. skipped checks */
            notes: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt: string | null;
        } | null;
        Error: {
            error: {
                /** @example not_found */
                code: string;
                message: string;
                details?: unknown;
            };
        };
        BusinessDetail: components["schemas"]["Business"] & {
            /** @description Signals from the latest audit, strongest first */
            signals: components["schemas"]["Signal"][];
            contacts: components["schemas"]["Contact"][];
        };
        Signal: {
            /** @enum {string} */
            axis: "need" | "capacity";
            /** @example slow_mobile */
            key: string;
            points: number;
            /** @example Google PageSpeed Insights rates the mobile performance 34/100. */
            evidence: string;
        };
        Contact: {
            /** @enum {string} */
            kind: "email" | "phone" | "whatsapp" | "instagram" | "facebook" | "tiktok" | "linkedin" | "other";
            value: string;
            sourceUrl: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
        };
    };
    listBusinesses: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tracked businesses with their latest audit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Business"][];
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    trackBusinesses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @example [
                     *       "klinik.co.id",
                     *       "https://www.sekolah-contoh.sch.id"
                     *     ]
                     */
                    websites: string[];
                };
            };
        };
        responses: {
            /** @description Businesses for the given websites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Business"][];
                        created: number;
                        skipped: {
                            input: string;
                            reason: string;
                        }[];
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The business */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BusinessDetail"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No business with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auditBusiness: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The audit was queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Audit"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No business with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
